/**
 * Korean administrative district romanization mappings
 * Based on Revised Romanization of Korean
 */

// Province/Metropolitan city romanization
export const provinceRomanization: Record<string, string> = {
  '서울특별시': 'Seoul',
  '부산광역시': 'Busan',
  '대구광역시': 'Daegu',
  '인천광역시': 'Incheon',
  '광주광역시': 'Gwangju',
  '대전광역시': 'Daejeon',
  '울산광역시': 'Ulsan',
  '세종특별자치시': 'Sejong',
  '경기도': 'Gyeonggi-do',
  '강원도': 'Gangwon-do',
  '강원특별자치도': 'Gangwon-do',
  '충청북도': 'Chungcheongbuk-do',
  '충청남도': 'Chungcheongnam-do',
  '전라북도': 'Jeollabuk-do',
  '전북특별자치도': 'Jeollabuk-do',
  '전라남도': 'Jeollanam-do',
  '경상북도': 'Gyeongsangbuk-do',
  '경상남도': 'Gyeongsangnam-do',
  '제주특별자치도': 'Jeju',
};

// County/City (시/군/구) romanization - comprehensive list
export const countyRomanization: Record<string, string> = {
  // 경기도
  '수원시': 'Suwon',
  '성남시': 'Seongnam',
  '고양시': 'Goyang',
  '용인시': 'Yongin',
  '부천시': 'Bucheon',
  '안산시': 'Ansan',
  '안양시': 'Anyang',
  '남양주시': 'Namyangju',
  '화성시': 'Hwaseong',
  '평택시': 'Pyeongtaek',
  '의정부시': 'Uijeongbu',
  '시흥시': 'Siheung',
  '파주시': 'Paju',
  '광명시': 'Gwangmyeong',
  '김포시': 'Gimpo',
  '군포시': 'Gunpo',
  '광주시': 'Gwangju',
  '이천시': 'Icheon',
  '양주시': 'Yangju',
  '오산시': 'Osan',
  '구리시': 'Guri',
  '안성시': 'Anseong',
  '포천시': 'Pocheon',
  '의왕시': 'Uiwang',
  '하남시': 'Hanam',
  '여주시': 'Yeoju',
  '양평군': 'Yangpyeong',
  '동두천시': 'Dongducheon',
  '과천시': 'Gwacheon',
  '가평군': 'Gapyeong',
  '연천군': 'Yeoncheon',

  // 강원도
  '춘천시': 'Chuncheon',
  '원주시': 'Wonju',
  '강릉시': 'Gangneung',
  '동해시': 'Donghae',
  '태백시': 'Taebaek',
  '속초시': 'Sokcho',
  '삼척시': 'Samcheok',
  '홍천군': 'Hongcheon',
  '횡성군': 'Hoengseong',
  '영월군': 'Yeongwol',
  '평창군': 'Pyeongchang',
  '정선군': 'Jeongseon',
  '철원군': 'Cheorwon',
  '화천군': 'Hwacheon',
  '양구군': 'Yanggu',
  '인제군': 'Inje',
  '고성군': 'Goseong',
  '양양군': 'Yangyang',

  // 충청북도
  '청주시': 'Cheongju',
  '충주시': 'Chungju',
  '제천시': 'Jecheon',
  '보은군': 'Boeun',
  '옥천군': 'Okcheon',
  '영동군': 'Yeongdong',
  '증평군': 'Jeungpyeong',
  '진천군': 'Jincheon',
  '괴산군': 'Goesan',
  '음성군': 'Eumseong',
  '단양군': 'Danyang',

  // 충청남도
  '천안시': 'Cheonan',
  '공주시': 'Gongju',
  '보령시': 'Boryeong',
  '아산시': 'Asan',
  '서산시': 'Seosan',
  '논산시': 'Nonsan',
  '계룡시': 'Gyeryong',
  '당진시': 'Dangjin',
  '금산군': 'Geumsan',
  '부여군': 'Buyeo',
  '서천군': 'Seocheon',
  '청양군': 'Cheongyang',
  '홍성군': 'Hongseong',
  '예산군': 'Yesan',
  '태안군': 'Taean',

  // 전라북도 / 전북특별자치도
  '전주시': 'Jeonju',
  '군산시': 'Gunsan',
  '익산시': 'Iksan',
  '정읍시': 'Jeongeup',
  '남원시': 'Namwon',
  '김제시': 'Gimje',
  '완주군': 'Wanju',
  '진안군': 'Jinan',
  '무주군': 'Muju',
  '장수군': 'Jangsu',
  '임실군': 'Imsil',
  '순창군': 'Sunchang',
  '고창군': 'Gochang',
  '부안군': 'Buan',

  // 전라남도
  '목포시': 'Mokpo',
  '여수시': 'Yeosu',
  '순천시': 'Suncheon',
  '나주시': 'Naju',
  '광양시': 'Gwangyang',
  '담양군': 'Damyang',
  '곡성군': 'Gokseong',
  '구례군': 'Gurye',
  '고흥군': 'Goheung',
  '보성군': 'Boseong',
  '화순군': 'Hwasun',
  '장흥군': 'Jangheung',
  '강진군': 'Gangjin',
  '해남군': 'Haenam',
  '영암군': 'Yeongam',
  '무안군': 'Muan',
  '함평군': 'Hampyeong',
  '영광군': 'Yeonggwang',
  '장성군': 'Jangseong',
  '완도군': 'Wando',
  '진도군': 'Jindo',
  '신안군': 'Sinan',

  // 경상북도
  '포항시': 'Pohang',
  '경주시': 'Gyeongju',
  '김천시': 'Gimcheon',
  '안동시': 'Andong',
  '구미시': 'Gumi',
  '영주시': 'Yeongju',
  '영천시': 'Yeongcheon',
  '상주시': 'Sangju',
  '문경시': 'Mungyeong',
  '경산시': 'Gyeongsan',
  '군위군': 'Gunwi',
  '의성군': 'Uiseong',
  '청송군': 'Cheongsong',
  '영양군': 'Yeongyang',
  '영덕군': 'Yeongdeok',
  '청도군': 'Cheongdo',
  '고령군': 'Goryeong',
  '성주군': 'Seongju',
  '칠곡군': 'Chilgok',
  '예천군': 'Yecheon',
  '봉화군': 'Bonghwa',
  '울진군': 'Uljin',
  '울릉군': 'Ulleung',

  // 경상남도
  '창원시': 'Changwon',
  '진주시': 'Jinju',
  '통영시': 'Tongyeong',
  '사천시': 'Sacheon',
  '김해시': 'Gimhae',
  '밀양시': 'Miryang',
  '거제시': 'Geoje',
  '양산시': 'Yangsan',
  '의령군': 'Uiryeong',
  '함안군': 'Haman',
  '창녕군': 'Changnyeong',
  '남해군': 'Namhae',
  '하동군': 'Hadong',
  '산청군': 'Sancheong',
  '함양군': 'Hamyang',
  '거창군': 'Geochang',
  '합천군': 'Hapcheon',

  // 제주도
  '제주시': 'Jeju',
  '서귀포시': 'Seogwipo',

  // 인천 구/군
  '강화군': 'Ganghwa',
  '옹진군': 'Ongjin',

  // 서울특별시 구
  '강남구': 'Gangnam',
  '강동구': 'Gangdong',
  '강북구': 'Gangbuk',
  '강서구': 'Gangseo',
  '관악구': 'Gwanak',
  '광진구': 'Gwangjin',
  '구로구': 'Guro',
  '금천구': 'Geumcheon',
  '노원구': 'Nowon',
  '도봉구': 'Dobong',
  '동대문구': 'Dongdaemun',
  '동작구': 'Dongjak',
  '마포구': 'Mapo',
  '서대문구': 'Seodaemun',
  '서초구': 'Seocho',
  '성동구': 'Seongdong',
  '성북구': 'Seongbuk',
  '송파구': 'Songpa',
  '양천구': 'Yangcheon',
  '영등포구': 'Yeongdeungpo',
  '용산구': 'Yongsan',
  '은평구': 'Eunpyeong',
  '종로구': 'Jongno',
  '중구': 'Jung',
  '중랑구': 'Jungnang',

  // 부산광역시 구/군
  '금정구': 'Geumjeong',
  '기장군': 'Gijang',
  '남구': 'Nam',
  '동구': 'Dong',
  '동래구': 'Dongnae',
  '부산진구': 'Busanjin',
  '북구': 'Buk',
  '사상구': 'Sasang',
  '사하구': 'Saha',
  '서구': 'Seo',
  '수영구': 'Suyeong',
  '연제구': 'Yeonje',
  '영도구': 'Yeongdo',
  '해운대구': 'Haeundae',

  // 대구광역시 구/군
  '달서구': 'Dalseo',
  '달성군': 'Dalseong',
  '수성구': 'Suseong',

  // 인천광역시 구
  '계양구': 'Gyeyang',
  '남동구': 'Namdong',
  '미추홀구': 'Michuhol',
  '부평구': 'Bupyeong',
  '연수구': 'Yeonsu',

  // 광주광역시 구
  '광산구': 'Gwangsan',

  // 대전광역시 구
  '대덕구': 'Daedeok',
  '유성구': 'Yuseong',

  // 울산광역시 구/군
  '울주군': 'Ulju',

  // 세종시
  '세종시': 'Sejong',

  // 행정시 (복합 구 형태) - 상위 시 이름만 사용
  '고양시덕양구': 'Goyang',
  '고양시일산동구': 'Goyang',
  '고양시일산서구': 'Goyang',
  '성남시분당구': 'Seongnam',
  '성남시수정구': 'Seongnam',
  '성남시중원구': 'Seongnam',
  '수원시권선구': 'Suwon',
  '수원시영통구': 'Suwon',
  '수원시장안구': 'Suwon',
  '수원시팔달구': 'Suwon',
  '안산시단원구': 'Ansan',
  '안산시상록구': 'Ansan',
  '안양시동안구': 'Anyang',
  '안양시만안구': 'Anyang',
  '용인시기흥구': 'Yongin',
  '용인시수지구': 'Yongin',
  '용인시처인구': 'Yongin',
  '부천시소사구': 'Bucheon',
  '부천시오정구': 'Bucheon',
  '부천시원미구': 'Bucheon',
  '전주시덕진구': 'Jeonju',
  '전주시완산구': 'Jeonju',
  '창원시마산합포구': 'Changwon',
  '창원시마산회원구': 'Changwon',
  '창원시성산구': 'Changwon',
  '창원시의창구': 'Changwon',
  '창원시진해구': 'Changwon',
  '천안시동남구': 'Cheonan',
  '천안시서북구': 'Cheonan',
  '청주시상당구': 'Cheongju',
  '청주시서원구': 'Cheongju',
  '청주시청원구': 'Cheongju',
  '청주시흥덕구': 'Cheongju',
  '포항시남구': 'Pohang',
  '포항시북구': 'Pohang',
};

/**
 * Get romanized name for a province
 */
export function romanizeProvince(name: string): string | undefined {
  return provinceRomanization[name];
}

/**
 * Get romanized name for a county/city
 */
export function romanizeCounty(name: string): string | undefined {
  return countyRomanization[name];
}
